baseURL = 'https://dgpconsult.com/'
languageCode = 'en-us'
title = 'DGPC - Data Guardian & Performance Consulting'
theme = 'PaperMod'
[params.profileMode]
    enabled = true
    title = "DGPC"
    subtitle = "Data Guardian & Performance Consulting"
    imageUrl = "logo2.png" 
    [[params.profileMode.buttons]]
        name = "Blog"
        url = "posts"
    [[params.profileMode.buttons]]
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/daniel-gustavo-pe%C3%B1a-chaves-dgpc/"
[[params.socialIcons]]
    name = "github"
    url = "https://github.com/Danielpe10"
[[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/daniel-gustavo-pe%C3%B1a-chaves-dgpc/"